FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04
RUN apt-get update && apt-get install -y python3-pip && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY ../.. /app
RUN pip3 install --no-cache-dir -r requirements.txt
ENV PYTHONUNBUFFERED=1
ENTRYPOINT ["bash", "training/docker/start.sh"]
